version: '3'
services:
  db:
    image: mysql:5.5
    volumes:
      - mysql_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_USER: root
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - "4306:3306"

  web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    environment:
      - AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY
      - BASIC_AUTH_USER
      - BASIC_AUTH_PASSWORD
    volumes:
      - .:/tubook:cached
      - /tubook/node_modules
      - bundle:/tubook/vendor/bundle
    ports:
      - "3000:3000"
    depends_on:
      - db
    tty: true
    stdin_open: true
volumes: 
  mysql_data:
  node_modules:
  bundle:
  